<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Only generates the XML doc when in debug mode -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.*" />
  </ItemGroup>

  <!-- Only use StyleCop when in debug mode -->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <!-- Setting private assets ensures this dependency is ignored in production -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <AdditionalFiles Include="../stylecop.json" />
  </ItemGroup>

</Project>
